### ISSUE TITLE
Failed installation.  npm ERR! opencv@6.0.0 install:

### ISSUE THREAD

**Issue by EdwinKestler** [DT42/BerryNet#22] opened 2018-02-13 15:11 UTC
![image](https://user-images.githubusercontent.com/4536353/36156814-d4db62f0-109d-11e8-91c3-cd76addb31ad.png)

erorr installing from fresh copy of stretch.

**Comment by bafu** [comment] 2018-07-08 15:17
The root cause is that OpenCV dev libraries do not be installed correctly, so node-opencv can not build correctly.

This issue is fixed in v2.3.0.

**Closed** 2018-07-08 15:17 UTC
